# Generated by Django 3.1.3 on 2020-12-02 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201202_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='date_of_passage',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='date_of_passage',
        ),
        migrations.AddField(
            model_name='result',
            name='dc',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата прохождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='dc',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата прохождения'),
            preserve_default=False,
        ),
    ]
