# Generated by Django 3.1.3 on 2020-12-21 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201202_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststudent',
            name='discipline',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Дисциплина'),
            preserve_default=False,
        ),
    ]
